### ISSUE TITLE
Dreamfactory Http services not working with post 

### ISSUE THREAD

**Issue by shajunr88** [dreamfactorysoftware/dreamfactory#169] opened 2017-11-17 08:50 UTC
I created a dreamfactory Http service and uses swagger to call it. It is pointing to external service named api.podio.com.I just given https://api.podio.com as the base url and created a swagger as follows 
`{
    "swagger": "2.0",
    "info": {
        "title": "podio API",
        "description": "Move your app forward with the podio API",
        "version": "1.0.0"
    },
    "host": "api.podio.com",
    "schemes": [
        "https"
    ],
    "basePath": "",
    "produces": [
        "application/json",
        "application/x-www-form-urlencoded"
    ],
    "paths": {

        "/oauth/token/" : {
          "post" : {
            "tags" : [ "OAuthorization" ],
            "summary" : "Get access token",
            "description" : "Gets a new access token for use when accessing the API.",
            "produces" : [ "application/json" ],
            "parameters" : [ 
             {
              "name" : "grant_type",
              "in" : "query",
              "required" : true,
              "type" : "string",
              "description" : "grant_type"
            },
            {
              "name" : "username",
              "in" : "query",
              "required" : true,
              "type" : "string",
              "description" : "username"
            },
            {
              "name" : "password",
              "in" : "query",
              "required" : true,
              "type" : "string",
              "description" : "password"
            },      
            {
              "name" : "client_id",
              "in" : "query",
              "required" : true,
              "type" : "string",
              "description" : "The key of the API client"
            }, {
              "name" : "client_secret",
              "in" : "query",
              "required" : true,
              "type" : "string",
              "description" : "The secret of the client. This will be generated by Podio and can be acquired in the API key area in Podio."
            }  ],
            "responses" : {
              "200" : {
                "description" : "Success",
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "access_token" : {
                      "type" : "string",
                      "description" : "The created access token. This is currently 128 characters long"
                    },
                    "token_type" : {
                      "type" : "string",
                      "description" : "The type of token, currently always \"bearer\""
                    },
                    "expires_in" : {
                      "type" : "number",
                      "description" : "The number of seconds until the access token expires and cannot be used anymore"
                    },
                    "refresh_token" : {
                      "type" : "string",
                      "description" : "The refresh token to use when a new access token is required because the access token expires"
                    },
                    "ref" : {
                      "type" : "object",
                      "description" : "The reference to the entity logged in",
                      "properties" : {
                        "type" : {
                          "type" : "string",
                          "description" : "The type of the entity, either \"user\" or \"app\""
                        },
                        "id" : {
                          "type" : "number"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
    }
}`
But when trying to call this from dream factory  it throws some exception 

`{
    "error": {
        "code": 400,
        "context": null,
        "message": "{&quot;error_parameters&quot;:[],&quot;error_detail&quot;:null,&quot;error_propagate&quot;:false,&quot;request&quot;:{&quot;url&quot;:&quot;http:\\/\\/api.podio.com\\/oauth\\/token&quot;,&quot;query_string&quot;:&quot;grant_type=password&amp;username=shajunr08%40gmail.com&amp;password=Test%401234&amp;client_id=test-apwx8dt&amp;client_secret=aasdasdasd&amp;redirect_uri=https%3A%2F%2Fconnect.thatapp.io&quot;,&quot;method&quot;:&quot;POST&quot;},&quot;error_description&quot;:&quot;Invalid value [\\&quot;password\\&quot;, \\&quot;password\\&quot;] (array): must be string&quot;,&quot;error&quot;:&quot;invalid_value&quot;}",`

I tried to call podio api from postman and its working fine.But through this dreamfactory its not working.

**Comment by todda48** [comment] 2017-11-17 14:02
By 'uses swagger to call it' do you mean from the API docs inside the DreamFactory admin console?
 You didn't mention what version of DreamFactory you are running, but starting with 2.10.0 you have to use version 3 of the OpenAPI spec (fka Swagger). There are online converters for this. The [release notes](http://wiki.dreamfactory.com/DreamFactory/Release_Notes#Version_2.10.0_.28Released_November_6.2C_2017.29) have some additional info.

Even with no OpenAPI service definition you should still be able to call the service using Postman using the DreamFactory URL, e.g., GET http://localhost:8080/api/v2/yourservice. If this is not working then there is likely something wrong with the service config in DreamFactory.

**Comment by drewpearce** [comment] 2017-11-17 16:02
Since this is not a bug, and you are already engaged with our support team, we will close this.

**Closed by drewpearce** 2017-11-17 16:02 UTC
Labels: help wanted
